service: sqstesttrigger

frameworkversion: '3'

provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
    

functions:
  hello:
    handler: handler.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:734386087821:demoqueue
          batchsize: 1
          enabled: true