

service: service-01-standart-queue

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  timeout: 300
  lambdaHashingVersion: "20201221"
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
  environment:
    sqs_url: !Sub https://sqs.us-east-1.amazonaws.com/${AWS::AccountId}/demoqueue
    sqs_url_dest: !Sub https://sqs.us-east-1.amazonaws.com/${AWS::AccountId}/demoqueue_dest

functions:
  sqsHandler:
    handler: handler.handler
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: true
